const deviceStencils = {
  "1U 2U Server": "mxgraph.citrix.1u_2u_server",
  "Access Card": "mxgraph.citrix.access_card",
  "Branch Repeater": "mxgraph.citrix.branch_repeater",
  Browser: "mxgraph.citrix.browser",
  "Cache Server": "mxgraph.citrix.cache_server",
  Calendar: "mxgraph.citrix.calendar",
  "Cell Phone": "mxgraph.citrix.cell_phone",
  Chassis: "mxgraph.citrix.chassis",
  "Citrix HDX": "mxgraph.citrix.citrix_hdx",
  "Citrix Logo": "mxgraph.citrix.citrix_logo",
  Cloud: "mxgraph.citrix.cloud",
  "Command Center": "mxgraph.citrix.command_center",
  Database: "mxgraph.citrix.database",
  "Database Server": "mxgraph.citrix.database_server",
  Datacenter: "mxgraph.citrix.datacenter",
  Desktop: "mxgraph.citrix.desktop",
  "Desktop Web": "mxgraph.citrix.desktop_web",
  "DHCP Server": "mxgraph.citrix.dhcp_server",
  "Directory Server": "mxgraph.citrix.directory_server",
  "DNS Server": "mxgraph.citrix.dns_server",
  Document: "mxgraph.citrix.document",
  "EdgeSight Server": "mxgraph.citrix.edgesight_server",
  Firewall: "mxgraph.citrix.firewall",
  "File Server": "mxgraph.citrix.file_server",
  "FTP Server": "mxgraph.citrix.ftp_server",
  "Geolocation Database": "mxgraph.citrix.geolocation_database",
  Globe: "mxgraph.citrix.globe",
  "GoTo Meeting": "mxgraph.citrix.goto_meeting",
  Government: "mxgraph.citrix.government",
  "Home Office": "mxgraph.citrix.home_office",
  "HQ Enterprise": "mxgraph.citrix.hq_enterprise",
  Inspection: "mxgraph.citrix.inspection",
  "IP Phone": "mxgraph.citrix.ip_phone",
  Kiosk: "mxgraph.citrix.kiosk",
  "Laptop 1": "mxgraph.citrix.laptop_1",
  "Laptop 2": "mxgraph.citrix.laptop_2",
  "License Server": "mxgraph.citrix.license_server",
  "Merchandising Server": "mxgraph.citrix.merchandising_server",
  Middleware: "mxgraph.citrix.middleware",
  "NetScaler Gateway": "mxgraph.citrix.netscaler_gateway",
  "NetScaler MPX": "mxgraph.citrix.netscaler_mpx",
  "NetScaler SDX": "mxgraph.citrix.netscaler_sdx",
  "NetScaler VPX": "mxgraph.citrix.netscaler_vpx",
  "PBX Server": "mxgraph.citrix.pbx_server",
  PDA: "mxgraph.citrix.pda",
  Podio: "mxgraph.citrix.podio",
  Printer: "mxgraph.citrix.printer",
  Process: "mxgraph.citrix.process",
  "Provisioning Server": "mxgraph.citrix.provisioning_server",
  "Proxy Server": "mxgraph.citrix.proxy_server",
  "Radius Server": "mxgraph.citrix.radius_server",
  "Remote Office": "mxgraph.citrix.remote_office",
  Reporting: "mxgraph.citrix.reporting",
  "Role AppController": "mxgraph.citrix.role_appcontroller",
  "Role Applications": "mxgraph.citrix.role_applications",
  "Role CloudBridge": "mxgraph.citrix.role_cloudbridge",
  "Role Desktops": "mxgraph.citrix.role_desktops",
  "Role Load Testing Controller": "mxgraph.citrix.role_load_testing_controller",
  "Role Load Testing Launcher": "mxgraph.citrix.role_load_testing_launcher",
  "Role Receiver": "mxgraph.citrix.role_receiver",
  "Role Repeater": "mxgraph.citrix.role_repeater",
  "Role Secure Access": "mxgraph.citrix.role_secure_access",
  "Role Security": "mxgraph.citrix.role_security",
  "Role Services": "mxgraph.citrix.role_services",
  "Role StoreFront": "mxgraph.citrix.role_storefront",
  "Role StoreFront Services": "mxgraph.citrix.role_storefront_services",
  "Role Synchronizer": "mxgraph.citrix.role_synchronizer",
  "Role XenMobile": "mxgraph.citrix.role_xenmobile",
  "Role XenMobile Device Manager":
    "mxgraph.citrix.role_xenmobile_device_manager",
  Router: "mxgraph.citrix.router",
  Security: "mxgraph.citrix.security",
  ShareFile: "mxgraph.citrix.sharefile",
  Site: "mxgraph.citrix.site",
  "SMTP Server": "mxgraph.citrix.smtp_server",
  "Storefront Services": "mxgraph.citrix.storefront_services",
  Switch: "mxgraph.citrix.switch",
  "Tablet 1": "mxgraph.citrix.tablet_1",
  "Tablet 2": "mxgraph.citrix.tablet_2",
  "Thin Client": "mxgraph.citrix.thin_client",
  "Tower Server": "mxgraph.citrix.tower_server",
  Users: "mxgraph.citrix.users",
  "User Control": "mxgraph.citrix.user_control",
  "Web Server": "mxgraph.citrix.web_server",
  "Web Service": "mxgraph.citrix.web_service",
  WorxEnroll: "mxgraph.citrix.worxenroll",
  WorxHome: "mxgraph.citrix.worxhome",
  WorxMail: "mxgraph.citrix.worxmail",
  WorxWeb: "mxgraph.citrix.worxweb",
  "XenApp Server": "mxgraph.citrix.xenapp_server",
  "XenApp Services": "mxgraph.citrix.xenapp_services",
  "XenApp Web": "mxgraph.citrix.xenapp_web",
  XenCenter: "mxgraph.citrix.xencenter",
  XenClient: "mxgraph.citrix.xenclient",
  "XenClient Synchronizer": "mxgraph.citrix.xenclient_synchronizer",
  "XenDesktop Server": "mxgraph.citrix.xendesktop_server",
  XenMobile: "mxgraph.citrix.xenmobile",
  XenServer: "mxgraph.citrix.xenserver"
};

export { deviceStencils };
